### ISSUE TITLE
CLI input option seems to not work 

### ISSUE THREAD

**Issue by therapon** [partiql/partiql-lang-kotlin#206] opened 2020-02-13 21:51 UTC
The following return no output 

```
echo "[1,2,3,4]"  | partiql --query="SELECT * FROM input_data"
partiql --i=nums.ion --query="SELECT * FROM input_data"
```

Where the file `nums.ion` contains `[1,2,3,4]`

**Comment by raganhan** [comment] 2020-02-24 23:28
The problem is that the output stream for the `PARTIQL` output format, which is default, is not closed so nothing is outputted.

Both examples work if you add `--of=ION_TEXT`. 

Fixed by: https://github.com/partiql/partiql-lang-kotlin/pull/225

**Closed** 2020-02-24 23:56 UTC
Labels: CLI, S, bug
