### ISSUE TITLE
ORDER by query using partiql

### ISSUE THREAD

**Issue by suryak** [partiql/partiql-lang-kotlin#134] opened 2019-10-23 02:51 UTC
Have been breaking my mind trying to get the order by query work with partiql.  My data is very simple: 
"data": [
        { "id": 3, "value": 1},
        { "id": 2, "value": 3},
        { "id": 1, "value": 2}
        ]
Can any one tell me how do I get order by done on the data above. 
Apologies if this is not the right place to ask this question. hope you can delegate me to the right group.

**Comment by therapon** [comment] 2019-10-23 15:08
`ORDER BY` is not implemented in the reference implementation, see #47

**Comment by dlurton** [comment] 2019-10-28 20:37
Duplicate of #47

**Closed by dlurton** 2019-10-28 20:37 UTC
