### ISSUE TITLE
Fix ExprValueFormatter for DATE and TIME.

### ISSUE THREAD

**Issue by abhikuhikar** [partiql/partiql-lang-kotlin#386] opened 2021-04-08 11:40 UTC
Change the `ExprValueFormatter` to output date literals as `DATE '<date_string>'` instead of just `<date_string>` and add the corresponding test to `ConfigurableExprValueFormatter`.

**Comment by abhikuhikar** [comment] 2021-12-20 20:19
Comparison operators are already implemented for `DATE` and `TIME`.

**Comment by johnedquinn** [comment] 2022-05-25 19:39
This could have unintended consequences, causing the inability to read our own output.

The extension function [ExprValue.stringify()](https://github.com/partiql/partiql-lang-kotlin/blob/79ce9f1ec8d198c43474c3919f21ac7c75b538a7/lang/src/org/partiql/lang/eval/ExprValueExtensions.kt#L164) uses the ConfigurableExprValueFormatter.format(), which calls [recursivePrettyPrint()](https://github.com/partiql/partiql-lang-kotlin/blob/79ce9f1ec8d198c43474c3919f21ac7c75b538a7/lang/src/org/partiql/lang/util/ExprValueFormatter.kt#L38).

So, if we modify the output ExprValueType.DATE and ExprValueType.TIME, we won't be able to read it back in. This issue would need to also modify the way we read PartiQL input files as well to understand the new DATE and TIME prefixes.

**Comment by dlurton** [comment] 2022-05-25 20:49
For background, `ExprValue.stringify()` is intended to produce valid PartiQL syntax representing the values, which should be parsable and result in an equivalent `ExprValue` when evaluated.  I am not entirely certain what the concern about not being abile to read our own output is--fixing that would seem to be the goal of this issue.

**Comment by dlurton** [comment] 2022-05-25 20:50
Also see: https://github.com/partiql/partiql-lang-kotlin/issues/567, which is related to this issue.

**Comment by dlurton** [comment] 2022-05-25 20:51
There's also https://github.com/partiql/partiql-lang-kotlin/issues/569 which I think is a duplicate of this issue and explains what's going on better.

**Comment by johnedquinn** [comment] 2022-05-26 19:30
Thanks for those links. Makes sense.

My concern deals with our inability to read PartiQL values (DATE and TIME) while reading input via the CLI. In my opinion, the CLI should allow input files to be both of the PartiQL and ION data formats.

There are ION files (.ion) which contain a subset of the allowed data types within PartiQL. The PartiQL date format is a superset (with types like DATE and TIME). The reason I had this question is because our default (and only) input file type for the CLI (--input) is ION, while the default output type is PARTIQL. If we output using type PARTIQL (default), it is impossible for us to read back in via the CLI input (only supporting subset ION).

IMO, we should:
- keep our defaults consistent. So, either input/output in ION or PARTIQL as default. I would say default to ION since we support this already (we don't support input PARTIQL).
- fix ExprValueFormatter for DATE and TIME (this issue)
- also fix our ION reader for $partiql_date (I can talk further on this)
- add a new CLI option --input-format (allowing ION (default) or PARTIQL) so that users can use --output-format PARTIQL and still read back in

LMK if you'd want to meet. Seems like there are a couple other things that should be addressed.

**Current Support**:
- CLI --input: allows ION (default)
- CLI --output-format: allows PARTIQL (default), PARTIQL_PRETTY, ION_TEXT, and ION_BINARY
- CLI FUNC read_file(): allows ION (default), CSV, TSV, EXCEL_CSV, MYSQL_CSV, POSTGRESQL_CSV, and POSTGRESQL_TEXT
- CLI FUNC write_file(): allows ION (default), CSV, TSV
- REPL input: no input. Only PartiQL environment struct.
- REPL output: always PartiQL data format.

**Comment by dlurton** [comment] 2022-05-26 20:37
So, this issue isn't limited to the CLI, of course.  The changes to the CLI that you propose above seem reasonable, but FWIW, probably don't belong in a PR that also fixes the formatting of `DATE` and `TIME` values.

**Closed** 2022-06-03 21:22 UTC
Labels: enhancement, good first issue, S
