### ISSUE TITLE
Scala support/bindings?

### ISSUE THREAD

**Issue by rwhaling** [partiql/partiql-lang-kotlin#120] opened 2019-08-06 14:25 UTC
Scala support would be great for integration into a lot of organizations' existing data pipelines and data engineering practices, mine included.  I tried to build the artifact locally with `./gradlew publishMavenLocal` and test it out in a Scala repl, but got this error when I tried to instantiate a `CompilerPipeline`:

```
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
  org.partiql.lang.CompilerPipeline$Companion.standard(CompilerPipeline.kt)
  org.partiql.lang.CompilerPipeline.standard(CompilerPipeline.kt)
  ammonite.$sess.cmd6$.<init>(cmd6.sc:1)
  ammonite.$sess.cmd6$.<clinit>(cmd6.sc)
java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
  java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  ammonite.runtime.SpecialClassLoader.findClass(ClassLoaders.scala:219)
  java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  org.partiql.lang.CompilerPipeline$Companion.standard(CompilerPipeline.kt)
  org.partiql.lang.CompilerPipeline.standard(CompilerPipeline.kt)
  ammonite.$sess.cmd6$.<init>(cmd6.sc:1)
  ammonite.$sess.cmd6$.<clinit>(cmd6.sc)
```

I have not tried to do Scala/Kotlin interop before, but I think this is a relatively mundane fat-jar/dependency packaging issue, and probably something that could be worked around?

**Comment by raganhan** [comment] 2019-08-13 17:47
Hi @rwhaling thanks for opening this issue. Would mind giving some steps to reproduce this, I'm not 100% sure on how you are testing PartiQL in the Scala REPL. 

As you mentioned I believe it could be dependency issues and not a problem with Scala interop. The maven artifact generated by `./gradlew publishMavenLocal` is not a fat jar so loading it directly into Scala REPL is not enough, you need to include all runtime dependencies as well.

**Comment by sksamuel** [comment] 2019-08-15 22:16
Try adding the kotlin sdk as well @rwhaling .
https://search.maven.org/artifact/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.3.41/jar

**Comment by raganhan** [comment] 2019-08-16 15:53
Take a look at https://github.com/partiql/partiql-lang-kotlin/blob/master/lang/build.gradle#L40-L41
The two runtime dependencies are: 
* [org.jetbrains.kotlin:kotlin-stdlib-jdk8](https://search.maven.org/artifact/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.3.41/jar)
* [com.amazon.ion:ion-java](https://search.maven.org/artifact/com.amazon.ion/ion-java/1.5.0/bundle)

We are in the process of publishing `partiql-kotlin-lang` in maven central. This will make it a lot easier since you'll be able to declare it as a dependency in SBT and it will take care of pulling in the rest, see https://github.com/partiql/partiql-lang-kotlin/issues/118

**Comment by rwhaling** [comment] 2019-08-16 18:39
awesome, thanks for taking a look!
yep, so I published the artifact to my local Ivy, but I didn't know how to bring in the kotlin stdlib via Maven, thanks for the tip.  Using ammonite, my preferred Scala repl, I can do this:
```
@ interp.repositories() ++= Seq(coursier.MavenRepository("file://" + @ import $ivy.`org.partiql.lang:partiql-lang-kotlin:0.1.0` 
@ import $ivy.`com.amazon.ion:ion-java:1.5.0` 
@ import $ivy.`org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.41` 
@ import com.amazon.ion.system.IonSystemBuilder 
@ import org.partiql.lang.CompilerPipeline 
@ import org.partiql.lang.eval.EvaluationSession 
@ import java.io.PrintStream 

@ val ion = IonSystemBuilder.standard().build() 
ion: com.amazon.ion.IonSystem = com.amazon.ion.impl.lite.IonSystemLite@5a78e7e3

@ val pipeline = CompilerPipeline.standard(ion) 
pipeline: CompilerPipeline = org.partiql.lang.CompilerPipelineImpl@703b2538

@ val session = EvaluationSession.standard() 
session: EvaluationSession = org.partiql.lang.eval.EvaluationSession@4190f278

@ val query = "1 + 1" 
query: String = "1 + 1"

@ print("PartiQL query:", query) 
(PartiQL query:,1 + 1)

@ val e = pipeline.compile(query) 
e: org.partiql.lang.eval.Expression = org.partiql.lang.eval.EvaluatingCompiler$compile$1@50ab5de4

@ val result = e.eval(session) 
result: org.partiql.lang.eval.ExprValue = 2

@ print("result", result.toString()) 
(result,2)
```

**Comment by raganhan** [comment] 2019-08-16 18:54
Awesome :)

Will close this issue since it seems like it's working well with Scala, . 

I opened https://github.com/partiql/partiql-lang-kotlin/issues/125 to add a Scala example to the Cookbook

**Closed by raganhan** 2019-08-16 18:54 UTC
